<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>RealTimeWeatherForChill</AssemblyName>
    <RootNamespace>RealTimeWeatherForChill</RootNamespace>
    <OutputPath>..\..\artifacts\QualityOfChilling.Weather\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GameDir Condition="'$(GameDir)' == '' and '$(CHILL_GAME_DIR)' != ''">$(CHILL_GAME_DIR)</GameDir>
    <GameDir Condition="'$(GameDir)' == ''">C:\program files (x86)\steam\steamapps\common\Chill with You Lo-Fi Story</GameDir>
    <BepInExRootDir Condition="'$(BepInExRootDir)' == '' and '$(BEPINEX_ROOT_DIR)' != ''">$(BEPINEX_ROOT_DIR)</BepInExRootDir>
    <BepInExRootDir Condition="'$(BepInExRootDir)' == ''">$(GameDir)</BepInExRootDir>
    <BepInExDir Condition="'$(BepInExDir)' == ''">$(BepInExRootDir)\BepInEx</BepInExDir>
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExDir)\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExDir)\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameDir)\Chill With You_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameDir)\Chill With You_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" PrivateAssets="all" />
  </ItemGroup>
</Project>
